# For more information about the configurations used in this file, please
# see the Travis CI documentation: https://docs.travis-ci.com

language: python
dist: xenial

python:
  - '3.6.4'

node_js:
  - "10"

cache:
  pip: true
  directories:
  - node_modules # NPM packages

services:
  - docker

env:
  global:
  - PGHOST=localhost
  - PGUSER=postgres
  - PGPORT=5432

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements/development.txt
  - nvm install v6.3.0
  - npm install -g npm
  - npm install

before_script:
- export DATABASE_URL=postgres://postgres@localhost/traviscircle
- psql -c "CREATE DATABASE traviscircle;" -U postgres

before_install:
  - sudo service postgresql stop
  - docker pull postgres:11
  - docker run --rm --name pg-docker -d -p ${PGPORT}:5432 --tmpfs /var/lib/postgresql/data:rw postgres:11
  - docker ps

script:
- flake8
- npm run build
- py.test --cov -v --tb=native
- ansible-playbook -i provisioner/hosts provisioner/site.yml --syntax-check

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
